[[main]]
  name = "Home"
  url = "/"
  weight = 1
[[main]]
  name = "About"
  url = "/project"
  weight = 2
[[main]]
  name = "Methodology"
  url = "/methodology"
  weight = 3
[[main]]
  name = "Results"
  url = "/results"
  weight = 4
[[main]]
  name = "Visualizations"
  url = "/visualizations"
  weight = 5
[[main]]
  name = "Team"
  url = "/team"
  weight = 6
[[main]]
  name = "Contact"
  url = "/contact"
  weight = 7
[[main]]
  name = "References"
  url = "/references"
  weight = 8